version: '3'

services:

  app:
    build: .
    container_name: "sm_web${SUFFIX}"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${PORT}:80"
    env_file: 
      - .env
